apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dep
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-dep
  template:
    metadata:
      labels:
        app: jenkins-dep
    spec:
      containers:
        - name: jenkins-dep
          image: jenkins/jenkins:lts
          command: ["/bin/sh", "-ec", "while :; do echo 'Hello World'; sleep 5 ; done"]
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: agent
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          hostPath:
            path: /home/user/jenkins_home
            type: DirectoryOrCreate
